# Generated by Django 4.2.8 on 2026-03-09 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_legal', models.CharField(blank=True, max_length=200)),
                ('nombre_complejo', models.CharField(blank=True, max_length=200)),
                ('id_fiscal', models.CharField(blank=True, max_length=50)),
                ('categoria_fiscal', models.CharField(blank=True, max_length=50)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('altura', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('telefono_comercial', models.CharField(blank=True, max_length=20)),
                ('email_comercial', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('amenities', models.ManyToManyField(blank=True, related_name='complexes', to='venues.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_complexes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Complexes',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sport', models.CharField(choices=[('futsal', 'Fútbol sala'), ('futbol7', 'Fútbol 7'), ('futbol11', 'Fútbol 11'), ('padel', 'Pádel'), ('tenis', 'Tenis'), ('waterpolo', 'Waterpolo'), ('pelota', 'Pelota vasca'), ('piscina', 'Piscina'), ('arco', 'Tiro con arco')], max_length=20)),
                ('surface', models.CharField(choices=[('cesped_sintetico', 'Césped sintético'), ('cesped_natural', 'Césped natural'), ('cemento', 'Cemento'), ('parquet', 'Parquet')], max_length=30)),
                ('has_lighting', models.BooleanField(default=False)),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lighting_extra_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='venues.complex')),
            ],
        ),
    ]
