# Generated by Django 4.2.8 on 2026-03-09 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS nombre_legal varchar(200) DEFAULT '';",
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS id_fiscal varchar(50) DEFAULT '';",
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS categoria_fiscal varchar(50) DEFAULT '';",
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS calle varchar(200) DEFAULT '';",
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS altura varchar(20) DEFAULT '';",
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS barrio varchar(100) DEFAULT '';",
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS telefono_comercial varchar(20) DEFAULT '';",
                "ALTER TABLE venues_complex ADD COLUMN IF NOT EXISTS email_comercial varchar(254) DEFAULT '';",
                "ALTER TABLE venues_complex ALTER COLUMN name TYPE varchar(200);",
                "ALTER TABLE venues_complex ALTER COLUMN city TYPE varchar(100);",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
