# Generated by Django 4.2.8 on 2026-03-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_drop_legacy_complex_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='address',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='nombre_complejo',
        ),
        migrations.AlterField(
            model_name='complex',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='complex',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
