# Generated by Django 4.2.8 on 2026-03-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_complex_address_remove_complex_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='court',
            name='sport',
            field=models.CharField(choices=[('futsal', 'Fútbol sala'), ('futbol7', 'Fútbol 7'), ('futbol11', 'Fútbol 11'), ('padel', 'Pádel'), ('tenis', 'Tenis'), ('waterpolo', 'Waterpolo'), ('pelota', 'Pelota vasca'), ('piscina', 'Piscina'), ('arco', 'Tiro con arco'), ('baloncesto', 'Baloncesto'), ('voleibol', 'Voleibol')], max_length=20),
        ),
    ]
