# Generated by Django 4.2.8 on 2026-02-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=100)),
                ('apellido_responsable', models.CharField(max_length=100)),
                ('dni_nie', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('telefono_responsable', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre_legal', models.CharField(max_length=200)),
                ('nombre_complejo', models.CharField(max_length=200)),
                ('id_fiscal', models.CharField(max_length=50)),
                ('categoria_fiscal', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=200)),
                ('altura', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('telefono_comercial', models.CharField(max_length=20)),
                ('email_comercial', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('deporte_preferido', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_jugador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
