# Generated by Django 4.2.8 on 2026-03-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='apellido_responsable',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='categoria_fiscal',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='email_comercial',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='id_fiscal',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombre_complejo',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombre_legal',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='nombre_responsable',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='telefono_comercial',
        ),
        migrations.AddField(
            model_name='propietario',
            name='complex',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='venues.complex'),
        ),
    ]
