# Generated by Django 4.2.8 on 2026-03-09 18:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Fecha y hora de inicio de la reserva')),
                ('end', models.DateTimeField(help_text='Fecha y hora de finalización de la reserva')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('confirmed', 'Confirmada'), ('in_progress', 'En curso'), ('finished', 'Finalizada'), ('cancelled', 'Cancelada')], default='pending_payment', help_text='Estado actual de la reserva', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio total a pagar por esta reserva', max_digits=10)),
                ('lighting', models.BooleanField(default=False, help_text='¿Se usará iluminación artificial?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó la reserva')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación')),
                ('court', models.ForeignKey(help_text='Cancha reservada', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.court')),
                ('user', models.ForeignKey(help_text='Usuario que realizó la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-start'],
            },
        ),
    ]
